version: '2.0'

services:
  # This will create a delve (https://github.com/go-delve/delve) container listening on tcp/2345 on our host for remote debugging
  # Simply point your IDE debugger to 127.0.0.1:2345 to debug your go app
  myapp_debug:
    security_opt:
      - seccomp:unconfined
    user: ${UID}:${GID}
    container_name: myapp_debug
    image: myapp_debug
    build:
      dockerfile: debug/dlv.Dockerfile
      context: .
    command:
      - /dlv
      - debug
      - --headless
      - --listen=:2345
      - --log
      - --api-version=2
      - --output
      - /src/bin/debug
    volumes:
      - ./.go:/go
      - ./.cache:/.cache
      - ./:/src:ro
      - ./bin:/src/bin
    working_dir: /src
    ports:
      - 2345:2345
      - 8080:8080
    networks:
      - net

networks:
  net:
