version: '2.1'

services:
  myapp:
    image: alpine:3.8
    user: ${UID:?err}:${GID:?err}
    entrypoint: /${BIN:?err}
    volumes:
      - ./${OUTBIN:?err}:/${BIN:?err}
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
